config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  resources :databases do
    resources :tables
    resources :circles
    resources :statuss
  end

  resources :tables do
    resources :columns
    resources :circles
  end

  resources :columns
  resources :circles

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact' 

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController

def index
    #@tables = Table.paginate(table: params[:table])
 end

def create
    @database = Database.find(params[:database_id])
    @table = @database.tables.create(params[:table])
    flash[:info] = "Table is created."
    redirect_to database_path(@database)
 end

 def show
  @tables = Table.find(params[:id])
  @databases = Database.all
    respond_to do |format|
    format.html  # show.html.erb
    format.json  { render :json => @tables }
  end
 end

 def edit
    @tables = Table.find(params[:id])
 end

 def update
    @tables = Table.find(params[:id])
    if @tables.update_attributes(params[:table])
      flash[:success] = "Table updated"
      redirect_to @tables
    else
      render 'edit'
    end         
  end

  def destroy
  @tables = Table.find(params[:id])
  @databases = Database.find_by_id(@tables.database_id)
  @tables.destroy
  
  redirect_to database_path(@databases) 
  end

end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_addcolumn.html.erb
<div id="modal_column" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
              <a class="close" data-dismiss="modal_column" >&times;</a>
              <h3>Add column</h3>
            </div>
            <div class="modal-body">
	
	
<%= form_for([@tables, @tables.columns.build]) do |f| %>

      <%= f.label :column_name %>
      <%= f.text_field :column_name %>

<%= f.label :column_type %>
<%= f.text_field :column_type %>

      <%= f.label :column_size_or_value %>
      <%= f.text_field :column_size %>

      <%= f.label :column_if_null %>
      <%= f.text_field :column_null %>

      <%= f.label :column_key %>
      <%= f.text_field :column_key %>

      <%= f.label :column_default %>
      <%= f.text_field :column_default %>

      <%= f.label :column_desc %>
      <%= f.text_area :column_desc, "rows" => 3 %>
	  
            <div class="modal-footer">
              <a href="#" class="btn " data-dismiss="modal" >colse</a>
              <%= f.submit "Add column", class: "btn btn-primary" %>
            </div>
<% end %>
 </div> </div>

app/views/tables/edit.html.erb
<h1>Table Admin</h1>
<h2>Edit table:</h2>
<div class="row">
  <div class="span6 offset3">

<%= form_for(@tables) do |f| %>

      <%= f.label :table_name %>
      <%= f.text_field :table_name %>

      <%= f.label :table_desc %>
      <%= f.text_area :table_desc, "rows" => 3 %>


      <%= f.submit "Update Tables", class: "btn btn-large btn-primary" %>
<% end %>
  
  </div>
</div>

app/views/tables/new.html.erb
<h1>Tables#new</h1>
<p>Find me in app/views/tables/new.html.erb</p>

app/views/tables/show.html.erb
<h1>Data Dictionary</h1>

            <table class="table">
              <thead>
                <tr>
                  <th><i class="icon-signal"></i></th>
                  <th>Table Name</th>
                  <th>Desc</th>
                  <th>Last modify change</th>
                  <% if admin_? %>
                  <th>Modify or Delete</th>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <tr class="success">
                  <td><%= @tables.id =%> </td>
                  <td><%= @tables.table_name =%> </td>
                  <td><%= @tables.table_desc =%> </td>
                  <td><%= @tables.updated_at =%> </td>
                 <% if admin_? %><td><%= link_to 'Edit', edit_table_path(@tables) %> / <%= link_to 'Destroy', @tables, :confirm => 'Are you sure?',:method => :delete %></td><% end %>
                </tr>
              </tbody>

              <thead>
                <tr>
                  <th><i class="icon-refresh"></i></th>
                  <th>Circle info</th>
                  <th>Sync type</th>
                  <th>Last modify change</th>
                  <% if admin_? %><th>Modify or Delete</th><% end %>
                </tr>
              </thead>
              <tbody>
                <% @tables.circles.each do |circle| %>
                <tr class="circle">

                  <% databases_circle = Database.find(circle.database_id)  %>
                  <td><%= circle.id =%> </td>
                  <td><%= link_to databases_circle.db_project , databases_circle =%></td>
                  <td><%= circle.circle_desc =%></td>
                  <td><%= circle.updated_at =%></td>
               <% if admin_? %> <td><%= link_to 'Edit', edit_table_path(@tables) %> / <%= link_to 'Destroy', @tables, :confirm => 'Are you sure?',:method => :delete %><% end %>
                </tr>
<% end %>
              </tbody>

            </table>
<% if admin_? %>
<a class="btn btn-primary btn-mini" id="backdroptrue" data-toggle="modal" href="#modalbackdroptrue" >Create Circle</a> 
<a class="btn btn-primary btn-mini" id="backdroptrue" data-toggle="modal" href="#modal_column" >Add Column</a> <br />
<% end %>
<%= render "tables/addcolumn" %>


<h2>Column List:</h2>
<div class="bs-docs-example">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Name</th>
                  <th>Type</th>
                  <th>Null</th>
                  <th>Key</th>
                  <th>Default</th>
                  <th>Desc</th>
                  <th>Last modify change</th>
                </tr>
              </thead>
              <tbody>
<% @tables.columns.each do |column| %>
                <tr>
                  <td><%= column.id =%> </td>
                  <td><%= column.column_name =%></td>
                  <td><%= column.column_type =%></td>
                  <td><%= column.column_null =%></td>
                  <td><%= column.column_key =%></td>
                  <td><%= column.column_default =%></td>
                  <td><%= column.column_desc =%> </td>
                  <td><%= column.updated_at =%> </td>
                </tr>
<% end %>
              </tbody>
            </table>
</div>

<!-- >
modal test
<-->

  
<!-- 是我,撑场面的注释条君 -->
<div id="modalbackdroptrue" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
              <a class="close" data-dismiss="modalbackdroptrue" >&times;</a>
              <h3>是我,撑场面的注释条君</h3>
            </div>
            <div class="modal-body">
              
<%= form_for([@tables, @tables.circles.build]) do |fc| %>
      <%= fc.label :circle_desc %>
      <%= fc.text_field :circle_desc %>

<select id="circle_database_id" name="circle[database_id]" >
                <% @databases.each do |databases| %>
                  <option value=<%= databases.id =%>><%= databases.db_name =%></option>
                <% end %>
</select>
<span class="label label-info">Info:这里讲创建表和表之间的同步关系。</span>
<%= hidden_field_tag("circle[circle_source]", @tables.database_id) %>
<%= hidden_field_tag(:table_id, @tables.id) %>

</div>

            <div class="modal-footer">
              <a href="#" class="btn " data-dismiss="modal" >colse</a>
              <%= fc.submit "Create Circle", class: "btn btn-primary" %>
             <!-- <a href="#" class="btn btn-primary"   >保存更改</a> -->
            </div>
            <% end %>   
</div><!-- 遥相呼应的注释君 1 -->
      
          